# Generated by Django 4.2.3 on 2023-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_event_location_booking_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
